# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sniff_pcap_ <- function(iface, filter, num, layers) {
    .Call(`_Rtins_sniff_pcap_`, iface, filter, num, layers)
}

